const icons: string[] = [
  "shopping_bag",
  "shopping_cart",
  "shopping_basket",
  "beach_access",
  "family_restroom",
  "directions_car",
  "child_care",
  "sailing",
  "two_wheeler",
  "public",
  "flight",
  "luggage",
  "child_friendly",
  "restaurant",
  "lunch_dining",
  "liquor",
  "local_pizza",
  "icecream",
  "local_cafe",
  "celebration",
  "cake",
  "school",
  "work",
  "apartment",
  "fitness_center",
  "local_hospital",
  "phone_iphone",
  "devices",
  "cabin",
  "hardware",
  "plumbing",
  "tv",
  "casino"
];

export default icons;
